#server:
#  port: ${PORT:9010}
#
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/product-order-service
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#
#logging:
#  level:
#    root: info
#    com:
#      example:
#        productorderservice: debug